FROM ubuntu:20.04

# Copying the script that installs necessary packages
COPY install_packages.sh /home/

# Making the script executable
RUN chmod +x /home/install_packages.sh

# Executing the install_packages.sh script to install necessary packages
RUN /home/install_packages.sh

# Copying the Web_Client script into the docker image
COPY Web_Client.py /home/

# Making the script executable
RUN chmod +x /home/Web_Client.py

CMD ["bash"]
